---
aide_packages:
  - aide
  - aide-common
aide_conf_file: /etc/aide/aide.conf
aide_confd_dir: /etc/aide/aide.conf.d
aide_exclusions_file: 70_exclusions.conf
aide_exclusions_path: "{{ aide_confd_dir }}/{{ aide_exclusions_file }}"
