---
galaxy_info:
  author: foo <bar@baz.com>
  description: "Configure auditd auditing daemon"
  min_ansible_version: "2.20.0"
  license: GPL-3.0-or-later
  platforms:
    - name: Debian
      versions:
        - trixie
  galaxy_tags:
    - debian
    - debian13
    - trixie
    - hardening
    - auditd
    - security
    - audit
    - mps-hardening
dependencies: []
