---
- name: Install apparmor packages
  ansible.builtin.apt:
    name: "{{ apparmor_packages }}"
    state: present
    update_cache: true
  become: true

- name: Sync custom apparmor profiles
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/etc/apparmor.d/"
    dest: /etc/apparmor.d/
    delete: false
    checksum: true
  become: true

- name: Ensure correct ownership for /etc/apparmor.d
  ansible.builtin.file:
    path: /etc/apparmor.d
    state: directory
    owner: root
    group: root
    mode: "0755"
    recurse: true
  become: true
