---
- name: Hardening common install
  hosts: all
  become: true
  roles:
    - role: mps.hardening.firewall
    - role: mps.hardening.apparmor
    - role: mps.hardening.auditd
    - role: mps.hardening.aide
