---
# Feature toggles — naming pattern: <rolename>_enable_<feature>

fail2ban_enable_service: true

# Regular configuration

fail2ban_packages:
  - fail2ban

fail2ban_jail_dir: /etc/fail2ban

fail2ban_jail_local_path: "{{ fail2ban_jail_dir }}/jail.local"

fail2ban_jail_d_dir: "{{ fail2ban_jail_dir }}/jail.d"

fail2ban_jail_sshd_path: "{{ fail2ban_jail_d_dir }}/sshd.local"

fail2ban_sshd_enabled: true
fail2ban_sshd_backend: systemd
fail2ban_sshd_port: ssh
fail2ban_sshd_logpath: /var/log/auth.log
fail2ban_sshd_maxretry: 5
fail2ban_sshd_findtime: 600
fail2ban_sshd_bantime: 600

fail2ban_service_name: fail2ban
